// <auto-generated />
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(QuizDbContext))]
    partial class QuizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Backend.Models.FloatingIds", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FloatingIds", (string)null);
                });

            modelBuilder.Entity("Backend.Models.FourOptionQuestion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectOptionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Option4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FourOptionQuestions", (string)null);

                    b.HasDiscriminator<string>("QuestionType").HasValue("FourOptionQuestion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Backend.Models.PlayerStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ListOfQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayerStatistics", (string)null);
                });

            modelBuilder.Entity("Backend.Models.QuestionTypes.ChemistryQuestion", b =>
                {
                    b.HasBaseType("Backend.Models.FourOptionQuestion");

                    b.HasDiscriminator().HasValue("Chemistry");
                });

            modelBuilder.Entity("Backend.Models.QuestionTypes.FoodQuestion", b =>
                {
                    b.HasBaseType("Backend.Models.FourOptionQuestion");

                    b.HasDiscriminator().HasValue("Food");
                });

            modelBuilder.Entity("Backend.Models.QuestionTypes.GameQuestion", b =>
                {
                    b.HasBaseType("Backend.Models.FourOptionQuestion");

                    b.HasDiscriminator().HasValue("Game");
                });

            modelBuilder.Entity("Backend.Models.QuestionTypes.GeographyQuestion", b =>
                {
                    b.HasBaseType("Backend.Models.FourOptionQuestion");

                    b.HasDiscriminator().HasValue("Geography");
                });

            modelBuilder.Entity("Backend.Models.QuestionTypes.HistoryQuestion", b =>
                {
                    b.HasBaseType("Backend.Models.FourOptionQuestion");

                    b.HasDiscriminator().HasValue("History");
                });

            modelBuilder.Entity("Backend.Models.QuestionTypes.LiteratureQuestion", b =>
                {
                    b.HasBaseType("Backend.Models.FourOptionQuestion");

                    b.HasDiscriminator().HasValue("Literature");
                });

            modelBuilder.Entity("Backend.Models.QuestionTypes.MathQuestion", b =>
                {
                    b.HasBaseType("Backend.Models.FourOptionQuestion");

                    b.HasDiscriminator().HasValue("Math");
                });

            modelBuilder.Entity("Backend.Models.QuestionTypes.MusicQuestion", b =>
                {
                    b.HasBaseType("Backend.Models.FourOptionQuestion");

                    b.HasDiscriminator().HasValue("Music");
                });

            modelBuilder.Entity("Backend.Models.QuestionTypes.SportsQuestion", b =>
                {
                    b.HasBaseType("Backend.Models.FourOptionQuestion");

                    b.HasDiscriminator().HasValue("Sports");
                });

            modelBuilder.Entity("Backend.Models.QuestionTypes.TechnologyQuestion", b =>
                {
                    b.HasBaseType("Backend.Models.FourOptionQuestion");

                    b.HasDiscriminator().HasValue("Technology");
                });
#pragma warning restore 612, 618
        }
    }
}
