using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Infrastructure.Models.Entities;

public class FloatingIds
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.None)] // The 'floating' Id should not be generated by the database
    public int Id { get; set; }
}
